### ISSUE TITLE
Finish Participant Code

### ISSUE THREAD

**Issue by djpetti** [djpetti/csci6780#18]
I don't know the exact planned design for the participant, so this is sort of a catch-all ticket. It might be worth splitting it up.

**Comment by Nickster258** [comment]
I am going to briefly go over my idea and plan for the participant code.

I am thinking of having 3 main tasks as part of a task pool managed by `participant.cpp`. This `participant.cpp` is ran by a `participant_main.cpp`, whose job it is to just run that single instance of `Participant`. The three tasks that the participant makes, and manages, are as follows:

1. `ConsoleTask`. This task's job is to take whatever input, depending upon the indication presented by the interface using it, and display it. The idea is that it will erase a line, replacing it with a message (in the case of a multicast receive), or print a new prompt. In just typing this out, I am realizing there is probably a better way, but I am floating this out there for now.
2. `MessengerTask`. This task's job is to manage the socket on its own thread and send received messages to the `ConsoleTask` for it to format accordingly. Since this task handles the socket connection, it will also send messages that can be received in an internal outgoing message queue.
3. `InputTask`. This task's job is to listen to the user's input and interject the necessary results into `ConsoleTask` and/or `MessageTask`.  This "task" doesn't have to be a task. It could be done in the main thread.

A few quick notes on my own ideas though. First, all of the necessary processes could probably be handled in just 2 threads without being that complicated. Second, I am not sure if implementing the participant this way is abusing the thread_pool system, rather than utilizing it.

In any event, those are my thoughts as of yet. I have already developed a method to "replace" a prompt in console and re-print the prompt to accept user input.
